version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - CalciumG
    reviewers:
      - CalciumG
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
