openapi: 3.0.3
info:
  title: Example App
  version: 0.0.0
  description: Example App API
servers:
  - url: "http://localhost:3000"
    description: Local
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: JohnDoe
        createdAt:
          type: string
          format: date-time
          example: "2023-07-15T10:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-07-15T10:00:00.000Z"
      required:
        - id
        - username
        - createdAt
        - updatedAt
    NewUser:
      type: object
      properties:
        username:
          type: string
          example: JohnDoe
      required:
        - username
    Error:
      title: Error
      type: object
      description: Generic error
      properties:
        statusCode:
          type: integer
        error:
          type: string
        message:
          type: string
      required:
        - statusCode
        - error
        - message
  responses:
    Error:
      description: Error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
tags:
  - name: example-app
paths:
  /api/users:
    get:
      summary: Get all users
      tags:
        - example-app
      responses:
        200:
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        500:
          $ref: "#/components/responses/Error"
    post:
      summary: Create a new user
      tags:
        - example-app
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUser"
      responses:
        201:
          description: The created user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          $ref: "#/components/responses/Error"
        500:
          $ref: "#/components/responses/Error"
